#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Matthew de Verteuil <mverteuil@github.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# ------------- Customize below -------------

export EDITOR="vim"
export PROJECT_HOME="$HOME/Codebase"
export PYENV_ROOT="$HOME/.pyenv"
