
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Use base16 shell
BASE16_SHELL="$HOME/.config/base16-shell/base16-embers.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

source /usr/local/bin/virtualenvwrapper.sh
if [[ -n $+functions[python-info] ]]; then
    python-info
fi

# Allow clobbering existing files
setopt CLOBBER

alias gst="git status"

# Load chruby
source /usr/local/opt/chruby/share/chruby/chruby.sh

# Shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Prompt
autoload -Uz promptinit
promptinit
prompt mverteuil
