#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Matthew de Verteuil <mverteuil@github.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ------------- Customize below -------------

# Aliases
alias blacken-changes-27="git diff --no-commit-id --name-only --diff-filter=d -r origin | grep \.py\$ | xargs black -l120 -tpy27"
alias blacken-changes-38="git diff --no-commit-id --name-only --diff-filter=d -ir origin | grep \.py\$ | xargs black -l120 -tpy38"
alias wipe-pycharm-helpers="docker ps -a | grep -i pycharm | awk '{print \$1}' | xargs docker rm && docker images | grep -i pycharm | awk '{print \$3}' | xargs docker rmi"

# Initialize nodenv, if it exists
if command -v nodenv 1>/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi

# Load iTerm2 shell integration, if it exists
if [[ -f "${ZDOTDIR:-$HOME}/.iterm2_shell_integration.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.iterm2_shell_integration.zsh"
fi

# Load G Adventures Okta function wrappers, if they exist
if [[ -f "$HOME/.okta/bash_functions" ]]; then
    . "$HOME/.okta/bash_functions"
fi

# Heroku Autocompletion
export HEROKU_AC_ZSH_SETUP_PATH=$HOME/Library/Caches/heroku/autocomplete/zsh_setup
test -f $HEROKU_AC_ZSH_SETUP_PATH && source $HEROKU_AC_ZSH_SETUP_PATH;
unset HEROKU_AC_ZSH_SETUP_PATH

# Allow file clobbering
setopt CLOBBER

# Load base16 shell integration, if it exists
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)

# Project switcher
if test ! -z $PROJECT_HOME; then
    function project () {
        cd $PROJECT_HOME/$1
    }

    function org () {
        cd $PROJECT_HOME/orgs/$1
    }

    # Project switched completion
    function _project () {
        _arguments -C \
        "1: :{_path_files -/ -W $PROJECT_HOME}"
    }

    function _org () {
        _arguments -C \
        "1: :{_path_files -/ -W $PROJECT_HOME/orgs}"
    }

    compdef _project project
    compdef _org org
else
    echo "------\nERROR: Project home was not set, project switcher not loaded.\n------\n"
fi


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
